#!/usr/bin/env bash
# Displays information about subdomains.

domain_information() {
    local domain="$1"
    local subdomain="$2"
    local line
    line=$(dig +short "$subdomain.$domain" | head -n 1)
    [ -n "$line" ] && echo "The subdomain $subdomain is a $(dig +short -t "$line" "$subdomain.$domain") record and points to $line"
}

if [ "$#" -eq 1 ]; then
    for subdomain in www lb-01 web-01 web-02; do
        domain_information "$1" "$subdomain"
    done
elif [ "$#" -eq 2 ]; then
    domain_information "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
fi
