#!/usr/bin/env bash
# Installs Nginx with the following configuration

sudo apt-get update
sudo apt-get install nginx
sudo ufw "Nginx HTTP"

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx reload
