#!/usr/bin/env bash

# Configures an Nginx server to listen on port 80.

# creates a symbolic link between the Nginx config file and the enabled sites dir
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restarts Nginx
service nginx start

# Terminates the first nginx process ID
kill "$(pgep 'nginx' | head -1)" 
